
function Do-Foo {
    param (
        $Level 
    )

    "I'm doing foo at the Level $Level ... ;-)"

}

Do-Foo -Level High

# SIG # Begin signature block
# MIIFXgYJKoZIhvcNAQcCoIIFTzCCBUsCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUY7sD6VfzgoWMOdi8tK77rCj2
# 28egggL+MIIC+jCCAeKgAwIBAgIQKLKj59ii+blK7mF2mEDQBzANBgkqhkiG9w0B
# AQsFADAVMRMwEQYDVQQDDApQUyBTaWduaW5nMB4XDTI0MDMyMDEzMjUzMloXDTI1
# MDMyMDEzNDUzMlowFTETMBEGA1UEAwwKUFMgU2lnbmluZzCCASIwDQYJKoZIhvcN
# AQEBBQADggEPADCCAQoCggEBAN9C4VnMrMMObeKloQI8ByFFCMCBR+HM2nn+i0JE
# +6JbhzAj0tj8KFxLMzy5TfesaueIL66hK9D3iIkS1CJvWydgN53uleqTeKB5cGE0
# oGKlUI84HxayQx173298jkzwVZjiGpyoXbqfMYfu8atmXTDmHJl4UtIZ3EX+WdDh
# zpSdC2RxkDLbemBMOnrG2yYFMjTSsW3LNUuITTR90Umlfi3V04RCL/6Ur5ZsSRLx
# f7PU/MFF5r+kczoAoFKTegtojJYviJflNLz1EH8TeetMofhVOvHNNpnqqHMI60Wr
# 2ZTB1OoB8lN0ob4DEDgOXqWjadW+Y/W2bdTh81VUKKrJeP0CAwEAAaNGMEQwDgYD
# VR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMB0GA1UdDgQWBBSpQsQQ
# bgvwwJcJ5Lfd1wuHepN3IjANBgkqhkiG9w0BAQsFAAOCAQEAnBbQR7sHqTaUdW/C
# SNbSmhyAbiDxeqS2dIoi2MZNxcn0iZ9C34jLwt3SWkKKHF98SyJkH6x5DNdFIwN2
# /ETpGNJvGw4nj1FB06GfQbGBVZlCDvC8jG8pDVxCoL412FgfIjkila9ZwpC/CTGo
# Uzzv/Ys0SxJvw0i/zFNSbDk3NnFfgke8e/pWz7VRg5FEkMub+/k4bM4hOcfgh3Qa
# ICZhByWS8r11ToaEjDWnpGUWTUp6ppHwI83/f6gSljLDqEdnMlz/RHLP6ijEz/M5
# hcBavkISaLQxwyXeteZI1icPSJyBt4q7nOwCGe6iQ5fP6vYGBhn+H3H4Hb57HY43
# gKigXTGCAcowggHGAgEBMCkwFTETMBEGA1UEAwwKUFMgU2lnbmluZwIQKLKj59ii
# +blK7mF2mEDQBzAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKA
# ADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYK
# KwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUaReVPc9Lk0ggHsSSFh7sYU6RbY0w
# DQYJKoZIhvcNAQEBBQAEggEAPV/YnhF/BgXzGfMLVfeMH7UROn7nBikxUFKO8Yh0
# 4N9Fk/nCZdgbaUSy6dlyZNPsKxVddTu7GkYs+mCfuvW2rMd/vMo8bEHAxlwNjBrU
# XphZ71x/Tgy0iYaXmGn0C3cyhunW0RjmCDqRRL39/TZ6OzGOYPtcrdYtRH7fQ/uP
# UzIWjgeHIu6yjRIKoyuUMEfHGxn4oSR1v64EfQ6WKWTvVb/TZbwMq3/z1rasjz/H
# kaUHR7s5+x0O/vzsHMyxHA4f7k0+MU6vHGH/rBLWSUmluU7m46ImeVG3hWLZwzeA
# 9MjtutyjAc5H6lcBYJtFbmr16q+hX7z+GhMjZQr1kaCoLg==
# SIG # End signature block
